name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
concurrency:
  group: "metrics"
  cancel-in-progress: false
jobs:
  repo-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Stats
        uses: lowlighter/metrics@latest
        with:
          token: ${{ github.token }}
          template: repository
          user: Exponential-Workload
          repo: ttyutil
          filename: metrics.svg
          committer_message: 'feat: Update Repo Metrics [skip ci]'
          plugin_introduction: yes
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_limit: 4
          plugin_languages_analysis_timeout: 15
          plugin_people: yes
          plugin_people_types: contributors, stargazers, watchers, sponsors
